"""fp2 agent-lifecycle-record parity corpus (ALR-1103).

ALR-1103's scope is narrow and deliberate: extend the *pinned* generic fp2
corpus (`tests/data/fp2_conformance.json`, `docs/fingerprints/fp2.md`,
`traigent_schema/fp2.py` -- none of which this story touches) with a second,
separately-scoped corpus of full manifest-shaped afp2/dfp2o/efp2/cfp2 cases
that pin the *parity scope* PART1_CONTRACT_FREEZE_DRAFT.md defines:

    "dfp2o/cfp2 equality remains independently tested across Python and
    JavaScript; afp2/efp2 determinism remains independently tested within
    one runtime." (PART1_CONTRACT_FREEZE_DRAFT.md:309)

TraigentSchema ships exactly one reference implementation. True cross-language
byte equality is proven the same way tests/test_fp2_conformance.py already
frames it: "Both SDKs run this same corpus." What this file checks, inside
this one repo, is the property that makes that convergence possible at all --
that the canonicalizer treats two semantically identical manifests built with
different key insertion order as byte-identical (a proxy for "two independent
implementations, given the same content, produce the same bytes") -- and,
symmetrically, that afp2/efp2's mandatory `runtime` discriminator actually
prevents an accidental cross-runtime match. The corpus lives at
tests/data/fp2/agent_lifecycle_cases.json and was generated by running the
real `traigent_schema.fp2.canonicalize`/`digest` functions, never hand-typed.

Mutation coverage (PART1_CONTRACT_FREEZE_DRAFT.md:1148, row 10): "Compare
afp2 or efp2 across runtimes" must fail exactly
`test_afp2_efp2_cross_runtime_digests_are_never_equal` below while the
dfp2o/cfp2 cross-runtime convergence tests stay green -- see the story's
mutation evidence in the PR/commit description for a hand-verified RED/GREEN
cycle of that exact edit.

Acceptance-criteria interpretation note (flagged per this story's brief, not
silently assumed): AC4 "Unknown fp2 fields preserve or fail closed" echoes
PART1_CONTRACT_FREEZE_DRAFT.md's SDK-contract bullet "preserve unknown
response fields/enums or fail closed without silently dropping them" --
which is written about wire *response* fields, an SDK-layer obligation this
Schema-only story cannot execute. The narrowest reading actually testable at
this layer is applied here: fp2's canonicalizer has no notion of a per-kind
allowed-key set, so an unrecognized manifest field is necessarily preserved
verbatim (never silently dropped), while a value fp2 genuinely cannot
represent fails the whole manifest closed (`Fp2UnsupportedValue`, never a
partial digest). `manifest_note` below is a corpus-only fixture key invented
to exercise this property; it is not proposed as real fp2/lifecycle
vocabulary and is not referenced by any schema.

Shared scaffolding note: several groups of tests below assert the same shape
against different corpus slices (an "offenders" filter that must come back
empty; a value that must fail closed on both fp2 entry points; a mutated
manifest that must digest differently). Each group shares one small helper or
one parametrize table rather than repeating the body, so the repeated
assertion pattern exists in exactly one place in this file.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path
from typing import Any, Callable

import pytest

from traigent_schema.fp2 import Fp2UnsupportedValue, canonicalize, digest

CORPUS = Path(__file__).resolve().parent / "data" / "fp2" / "agent_lifecycle_cases.json"

# Same substitution convention as tests/test_fp2_conformance.py: markers let
# JSON express values it cannot natively hold, substituted by each harness
# with the language's native equivalent. Only the two markers this corpus
# actually uses are declared here.
_MARKERS: dict[str, Any] = {
    "@@NAN@@": float("nan"),
    "@@LONE_SURROGATE@@": "a\ud800b",
}

_VALID_SCOPES = {"cross_runtime", "within_runtime_only", "preserve_unknown", "fail_closed"}
_WITHIN_RUNTIME_FAMILIES = (
    "agent_basic",
    "agent_bound_state",
    "evaluator_source",
    "evaluator_external",
)


def _cases() -> list[dict[str, Any]]:
    return json.loads(CORPUS.read_text(encoding="utf-8"))["cases"]


def _substitute(value: Any) -> Any:
    if isinstance(value, str) and value in _MARKERS:
        return _MARKERS[value]
    if isinstance(value, list):
        return [_substitute(item) for item in value]
    if isinstance(value, dict):
        return {key: _substitute(item) for key, item in value.items()}
    return value


def _ok_cases() -> list[dict[str, Any]]:
    return [case for case in _cases() if case["expect"] == "ok"]


def _unsupported_cases() -> list[dict[str, Any]]:
    return [case for case in _cases() if case["expect"] == "unsupported"]


def _cases_by_runtime_for_family(family: str) -> dict[str, dict[str, Any]]:
    return {case["runtime"]: case for case in _cases() if case.get("family") == family}


def _case_named(name: str) -> dict[str, Any]:
    return next(c for c in _cases() if c["name"] == name)


def _assert_no_offenders(offenders: list[str], message: str) -> None:
    assert not offenders, f"{message}: {offenders}"


def _assert_fails_closed(value: Any) -> None:
    """Both fp2 entry points must refuse a manifest they cannot represent."""
    with pytest.raises(Fp2UnsupportedValue):
        canonicalize(value)
    with pytest.raises(Fp2UnsupportedValue):
        digest(value)


def test_corpus_exists_and_is_non_trivial() -> None:
    cases = _cases()
    assert len(cases) >= 15, "a corpus this small cannot pin the fp2 lifecycle parity scope"


def test_case_names_are_unique() -> None:
    names = [case["name"] for case in _cases()]
    assert len(names) == len(set(names)), "duplicate case names make failures ambiguous"


def test_every_case_declares_a_recognized_scope() -> None:
    offenders = [case["name"] for case in _cases() if case.get("scope") not in _VALID_SCOPES]
    _assert_no_offenders(offenders, "cases with an unrecognized scope")


def test_every_fp2_kind_used_by_the_lifecycle_record_is_represented() -> None:
    kinds = {case["kind"] for case in _cases()}
    assert kinds == {"afp2", "dfp2o", "efp2", "cfp2"}


def test_case_kind_matches_the_manifest_kind_property() -> None:
    offenders = [case["name"] for case in _cases() if case["value"].get("kind") != case["kind"]]
    _assert_no_offenders(offenders, "case.kind disagrees with value.kind")


@pytest.mark.parametrize("case", _ok_cases(), ids=lambda c: c["name"])
def test_ok_case_canonicalizes_and_digests_as_recorded(case: dict[str, Any]) -> None:
    value = _substitute(case["value"])
    assert canonicalize(value) == case["canonical"]
    assert digest(value) == case["digest"]


@pytest.mark.parametrize("case", _unsupported_cases(), ids=lambda c: c["name"])
def test_unsupported_case_fails_closed_on_both_entry_points(case: dict[str, Any]) -> None:
    _assert_fails_closed(_substitute(case["value"]))


def test_dfp2o_and_cfp2_never_carry_a_runtime_discriminator() -> None:
    """dfp2o/cfp2 are required to match across languages; fp2.md: they
    'carry no such field' -- a runtime token would break exactly the parity
    they exist to provide."""
    offenders = [
        case["name"]
        for case in _cases()
        if case["kind"] in {"dfp2o", "cfp2"} and "runtime" in case["value"]
    ]
    _assert_no_offenders(offenders, "dfp2o/cfp2 cases smuggling a runtime scope")


def test_afp2_and_efp2_always_carry_a_runtime_discriminator() -> None:
    offenders = [
        case["name"]
        for case in _cases()
        if case["kind"] in {"afp2", "efp2"}
        and case["value"].get("runtime") not in ("python", "javascript")
    ]
    _assert_no_offenders(offenders, "afp2/efp2 cases with a missing/malformed runtime scope")


# ---------------------------------------------------------------------------
# AC1 / AC2 -- dfp2o is byte-equal cross-runtime for a canonical object;
# cfp2 is byte-equal cross-runtime for a canonical contract/configuration.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("family", ["dataset_convergence", "config_convergence"])
def test_cross_runtime_scope_kinds_converge_regardless_of_construction_order(family: str) -> None:
    """Two manifests built with different key insertion order -- standing in
    for two independently-written SDK manifest builders -- must canonicalize
    to byte-identical output. A canonicalizer that leaked construction order
    (e.g. iterating insertion order instead of sorting) would still pass
    every single-value case in tests/data/fp2_conformance.json and only fail
    here."""
    variants = [case for case in _cases() if case.get("family") == family]
    assert len(variants) >= 2, f"{family} needs at least two construction-order variants"

    canonical_texts = {canonicalize(case["value"]) for case in variants}
    digests = {digest(case["value"]) for case in variants}

    assert len(canonical_texts) == 1, (
        f"{family} variants diverged in canonical text: {canonical_texts}"
    )
    assert len(digests) == 1, f"{family} variants diverged in digest: {digests}"
    assert {case["digest"] for case in variants} == digests, (
        "recorded digest drifted from computed digest"
    )


def test_dfp2o_row_order_is_significant_not_convergent() -> None:
    """The deliberate non-convergent case: row order changes the digest
    (fp2.md: 'Row order is significant... An order-independent digest would
    declare those two runs comparable')."""
    ordered = _case_named("dfp2o_dataset_convergence_input_first")
    reversed_ = _case_named("dfp2o_dataset_row_order_reversed_differs")

    assert digest(ordered["value"]) != digest(reversed_["value"])


# ---------------------------------------------------------------------------
# AC3 -- afp2 and efp2 are deterministic only within each runtime; no
# cross-runtime claim. This is the "fp2 scope test" from
# PART1_CONTRACT_FREEZE_DRAFT.md:1148 (mutation row 10): "Compare afp2 or
# efp2 across runtimes" must fail
# test_afp2_efp2_cross_runtime_digests_are_never_equal while dfp2o/cfp2
# convergence above stays green.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("family", _WITHIN_RUNTIME_FAMILIES)
def test_afp2_efp2_are_deterministic_within_one_runtime(family: str) -> None:
    by_runtime = _cases_by_runtime_for_family(family)
    assert set(by_runtime) == {"python", "javascript"}

    for case in by_runtime.values():
        assert digest(case["value"]) == digest(case["value"]) == case["digest"]


@pytest.mark.parametrize("family", _WITHIN_RUNTIME_FAMILIES)
def test_afp2_efp2_cross_runtime_digests_are_never_equal(family: str) -> None:
    """THE fp2 scope negative. Flipping the final assertion to `==` is this
    story's named failure mutation and must turn this test red while the
    dfp2o/cfp2 convergence tests above stay green -- see mutation evidence."""
    by_runtime = _cases_by_runtime_for_family(family)
    python_case = by_runtime["python"]
    javascript_case = by_runtime["javascript"]

    # Guard the test itself: the two sides must share identical non-runtime
    # content, or a digest mismatch would prove nothing about runtime scope.
    python_content = {k: v for k, v in python_case["value"].items() if k != "runtime"}
    javascript_content = {k: v for k, v in javascript_case["value"].items() if k != "runtime"}
    assert python_content == javascript_content, (
        f"{family} python/javascript variants must share identical non-runtime content "
        "for this to be a real scope test rather than an accidental digest mismatch"
    )

    assert digest(python_case["value"]) != digest(javascript_case["value"])


# ---------------------------------------------------------------------------
# AC4 -- unknown fp2 fields preserve or fail closed (see module docstring for
# the interpretation this story applies).
# ---------------------------------------------------------------------------


def test_unknown_manifest_field_is_preserved_not_dropped() -> None:
    case = next(c for c in _cases() if c["scope"] == "preserve_unknown")
    canonical = canonicalize(case["value"])

    assert canonical == case["canonical"]
    # Reparse the canonical text: the field none of fp2's four algorithms
    # name must survive byte-for-byte, not merely appear as a substring.
    reparsed = json.loads(canonical)
    assert reparsed["manifest_note"] == case["value"]["manifest_note"]


def test_unsupported_value_fails_the_whole_manifest_closed_across_all_kinds() -> None:
    """The other half of AC4: what fp2 cannot represent it refuses whole --
    never a digest with some fields silently dropped -- for every one of the
    four manifest kinds, not just one. Reuses the same _assert_fails_closed
    helper as test_unsupported_case_fails_closed_on_both_entry_points above;
    this test's own contribution is the coverage assertion below."""
    fail_closed_cases = [c for c in _cases() if c["scope"] == "fail_closed"]
    assert {c["kind"] for c in fail_closed_cases} == {"afp2", "dfp2o", "efp2", "cfp2"}

    for case in fail_closed_cases:
        _assert_fails_closed(_substitute(case["value"]))


# ---------------------------------------------------------------------------
# AC5 -- a canonical input mutation changes the digest and turns the corpus
# red.
# ---------------------------------------------------------------------------


def _mutate_dataset_row(value: dict[str, Any]) -> None:
    value["rows"][0]["expected"] = "5"  # was "4"


def _mutate_configuration_space(value: dict[str, Any]) -> None:
    value["space"]["temperature"] = [0.2, 0.9]  # was [0.1, 0.9]


def _mutate_agent_source_text(value: dict[str, Any]) -> None:
    value["source"] = value["source"].replace("1.0", "2.0")


# (case name, in-place mutator, also assert the canonical text changed too)
# The dataset-row case additionally pins canonical-text sensitivity, not just
# digest sensitivity; the other two only need the digest check to demonstrate
# AC5.
_DIGEST_MUTATION_CASES: tuple[tuple[str, Callable[[dict[str, Any]], None], bool], ...] = (
    ("dfp2o_dataset_convergence_input_first", _mutate_dataset_row, True),
    ("cfp2_config_convergence_model_first", _mutate_configuration_space, False),
    ("afp2_agent_basic_python", _mutate_agent_source_text, False),
)


@pytest.mark.parametrize(
    "case_name,mutate,also_assert_canonical_changed",
    _DIGEST_MUTATION_CASES,
    ids=[case_name for case_name, _, _ in _DIGEST_MUTATION_CASES],
)
def test_mutating_a_canonical_input_changes_the_digest(
    case_name: str,
    mutate: Callable[[dict[str, Any]], None],
    also_assert_canonical_changed: bool,
) -> None:
    case = _case_named(case_name)
    mutated = copy.deepcopy(case["value"])
    mutate(mutated)

    assert digest(mutated) != case["digest"]
    if also_assert_canonical_changed:
        assert canonicalize(mutated) != case["canonical"]
